import csv

mappings = {
    "Nezha": "Wild Spark",
    "Han Xin": "Windspear",
    "Fuzi": "Wise Sage",
    "Consort Yu": "Woodland Ranger",
    "Sun Bin": "Timebender",
    "Liang": "Tomemaster",
    "Yang Jian": "Trilight",
    "Yuhuan": "Tunecaster",
    "Bai Qi": "Ultimate Weapon",
    "Lu Bu": "Unrivaled Warrior",
    "Xiang Yu": "Unyielding Overlord",
    "Li Xin": "Vengeance",
    "Kui": "Voidcaller",
    "Guan Yu": "War Saint",
    "Ata": "White Anchor",
    "Agudo": "Wild Rider",
    "Gan & Mo": "Smith and Blade",
    "Hou Yi": "Solarus",
    "Augran": "Soulguide",
    "Biron": "Sparkmace",
    "Ming": "Star Teller",
    "Yao": "Starblade",
    "Flowborn (Marksman)": "Steady Will",
    "Lam": "Stealthfin",
    "Ukyo Tachibana": "Swift Strike",
    "Musashi": "Swordmaster",
    "Zhang Fei": "The Beast",
    "Pei": "Tigerous",
    "Alessio": "Red Hawk",
    "Lapulapu": "Reefheart Datu",
    "Charlotte": "Rose Fencer",
    "Athena": "Sacred Warrior",
    "Angela": "Scorchette",
    "Sun Ce": "Seafarer",
    "Dolia": "Seasinger",
    "Gao Changgong": "Shadowblade",
    "Sima Yi": "Shadowreaper",
    "Arke": "Shadowstalker",
    "Shi": "Silkweaver",
    "Wuyan": "Sledgehammer",
    "Umbrosa": "Nightplume",
    "Chano": "Packleader",
    "Arthur": "Paladin",
    "Arli": "Parasola",
    "Flowborn (Tank)": "Peaceful Fist",
    "Mozi": "Peacekeeper",
    "Garo": "Piercing Arrow",
    "Liu Bei": "Pointblank",
    "Wang Zhaojun": "Princess Frost",
    "Fang": "Private Ear",
    "Mi Yue": "Raveness",
    "Cirrus": "Razorwing",
    "Xuance": "Madlash",
    "Di Renjie": "Magistrate",
    "Garuda": "Majestic Guardian",
    "Mayene": "Martial Genius",
    "Dharma": "Martial Monk",
    "Kongming": "Mastermind",
    "Liu Shan": "Mecha Brat",
    "Luban No.7": "Mecha Shooter",
    "Milady": "Mechaboss",
    "Fatih": "Mighty Conqueror",
    "Wukong": "Monkey King",
    "Luna": "Moonblade",
    "Nakoruru": "Hawk Whisperer",
    "Cai Yan": "Healing Tone",
    "Daji": "Heartseeker",
    "Zhou Yu": "Inferno",
    "Mulan": "Ironbloom",
    "Da Qiao": "Lanternlight",
    "Erin": "Laurel Princess",
    "Shouyue": "Longshot",
    "Ao'yin": "Loong",
    "Meng Ya": "Loose Cannon",
    "Diaochan": "Lotusdancer",
    "Li Bai": "Lyricist",
    "Haya": "Evernight Aspiration",
    "Gao": "Fatal Lyrist",
    "Heino": "Fateturner",
    "Zilong": "Fearless Spear",
    "Feyd": "Featherfoot",
    "Mai Shiranui": "Fireninja",
    "Luara": "Firesnake",
    "Ying": "Firespear",
    "Chicha": "Forge Maiden",
    "Allain": "Forgotten Blade",
    "Marco Polo": "Gunslinger",
    "Donghuang": "Harbinger",
    "Lady Sun": "Cannon Belle",
    "Lady Zhen": "Cascada",
    "Nuwa": "Celestial",
    "Dr Bian": "Curious Mixture",
    "Butterfly": "Death's Whisper",
    "Yaria": "Deerie",
    "Kaizer": "Demonplate",
    "Ziya": "Divine Enforcer",
    "Liu Bang": "Dominant Ruler",
    "Menki": "Dream Spirit",
    "Zhuangzi": "Dreamwanderer",
    "Lian Po": "Earthshaker",
    "Guiguzi": "Animist",
    "Flowborn (Mage)": "Arcane Heart",
    "Huang Zhong": "Artillerist",
    "Yango": "Avici Puppeteer",
    "Dun": "Belligerence",
    "Dian Wei": "Berserker",
    "Yixing": "Boardmaster",
    "Dyadia": "Bondweaver",
    "Xiao Qiao": "Breezeheart",
    "Jing": "Broken Mirage",
    "Sakeer": "Brushstrider",
    "Shangguan": "Calligrapher"
}

with open("hero_mappings.csv", "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerow(["Chinese Name", "English Name"])
    for ch_name, en_name in mappings.items():
        writer.writerow([ch_name, en_name])

print(f"Successfully wrote {len(mappings)} mappings to hero_mappings.csv")
